apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-analyst
resources:
  - ../../open-analyst
  - postgres.yaml
  - minio.yaml
patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
  - path: webapp-patch.yaml
  - path: runtime-patch.yaml
  - path: analyst-mcp-patch.yaml
  - path: keycloak-patch.yaml
