apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - webapp.yaml
  - runtime.yaml
  - analyst-mcp.yaml
  - keycloak.yaml
  - ingress.yaml
